{"Timestamp":"2021-10-12T14:50:55.7399224+03:00","Level":"Information","MessageTemplate":"Start processing HTTP request {HttpMethod} {Uri}","RenderedMessage":"Start processing HTTP request \"POST\" http://localhost:5001/api/products","Properties":{"HttpMethod":"POST","Uri":"http://localhost:5001/api/products","EventId":{"Id":100,"Name":"RequestPipelineStart"},"SourceContext":"System.Net.Http.HttpClient.WebStoreAPI.LogicalHandler","ActionId":"205d852b-ec63-431a-bc62-fada89db58e9","ActionName":"WebStore.Controllers.HomeController.Index (WebStore)","RequestId":"0HMCDEQ51PBMS:00000002","RequestPath":"/","ConnectionId":"0HMCDEQ51PBMS","Scope":["HTTP POST http://localhost:5001/api/products"],"Application":"Sample"}},{"Timestamp":"2021-10-12T14:50:56.3357350+03:00","Level":"Information","MessageTemplate":"Sending HTTP request {HttpMethod} {Uri}","RenderedMessage":"Sending HTTP request \"POST\" http://localhost:5001/api/products","Properties":{"HttpMethod":"POST","Uri":"http://localhost:5001/api/products","EventId":{"Id":100,"Name":"RequestStart"},"SourceContext":"System.Net.Http.HttpClient.WebStoreAPI.ClientHandler","ActionId":"205d852b-ec63-431a-bc62-fada89db58e9","ActionName":"WebStore.Controllers.HomeController.Index (WebStore)","RequestId":"0HMCDEQ51PBMS:00000002","RequestPath":"/","ConnectionId":"0HMCDEQ51PBMS","Scope":["HTTP POST http://localhost:5001/api/products"],"Application":"Sample"}},{"Timestamp":"2021-10-12T18:18:11.7780125+03:00","Level":"Error","MessageTemplate":"An unhandled exception has occurred while executing the request.","RenderedMessage":"An unhandled exception has occurred while executing the request.","Exception":"System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (localhost:5001))\r\n ---> System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (localhost:5001)\r\n ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)\r\n   at WebStore.WebAPI.Clients.Base.BaseClient.PostAsync[T](String url, T item, CancellationToken Cancel) in D:\\WebStore[2021-09-14T19-30-42]\\WebStore\\Services\\WebStore.WebAPI.Clients\\Base\\BaseClient.cs:line 33\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at WebStore.WebAPI.Clients.Base.BaseClient.Post[T](String url, T item) in D:\\WebStore[2021-09-14T19-30-42]\\WebStore\\Services\\WebStore.WebAPI.Clients\\Base\\BaseClient.cs:line 30\r\n   at WebStore.WebAPI.Clients.Products.ProductsClient.GetProducts(ProductFilter Filter) in D:\\WebStore[2021-09-14T19-30-42]\\WebStore\\Services\\WebStore.WebAPI.Clients\\Products\\ProductsClient.cs:line 43\r\n   at WebStore.Controllers.HomeController.Index(IProductData ProductData) in D:\\WebStore[2021-09-14T19-30-42]\\WebStore\\UI\\WebStore\\Controllers\\HomeController.cs:line 20\r\n   at lambda_method1(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","Properties":{"EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"0HMCDEQ51PBMS:00000002","RequestPath":"/","ConnectionId":"0HMCDEQ51PBMS","Application":"Sample"}},